spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  mail:
#    host: localhost
#    port: 1025
#    username: user
#    password: pass
#    properties:
#      mail:
#        smtp:
#          trust: "*"
#        auth: true
#        starttls:
#          enable: true
#        connectiontimeout: 5000
#        timeout: 3000
#        writetimeout: 5000mail:
    protocol: smtp
    host: ${EMAIL_HOST_NAME}
    port: 587
#    username: twilighttom493@gmail.com
    username: ${EMAIL_USERNAME}
#    password: qqyx pciv xcef osgi
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8088

application:
  security:
    jwt:
      secret-key: 454f524d58567251787a366b356e65706d534d3453347552566855756b466273
      expiration: 86400000
  mailing:
      frontend:
        activation-url: http://localhost:4200/activate-account
  cors:
    origins: http://192.168.0.227:8088/,http://localhost:8088/,http://localhost:4200,http://192.168.0.227:8080
  file:
    upload:
      photos-output/path: ./uploads